server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://rcdb.camd5cd2mgun.ap-northeast-2.rds.amazonaws.com/idus?autoReconnect=true # 변경해주세요
    username: dee0329 # 변경해주세요
    password: 8597wprkfRB! # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전